version: '3'

services:
  php:
    build:
      context: .
    volumes:
      - ./:/var/www/html

  web:
    image: nginx:1.17
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - .docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  # node:
  #   image: node:12
  #   user: node
  #   working_dir: /assets
  #   volumes:
  #     - ./:/assets
  #   command: npm run watch

  db:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mysqldata:/var/lib/mysql

  redis:
    image: redis:5
    volumes:
      - redisdata:/data

volumes:
  mysqldata:
  redisdata:







# version: '3'

# services:
#   nginx:
#     build:
#       context: ./docker/nginx
#       dockerfile: DockerfileDEV
#     image: ${BASE_TAG:-laravel}/nginx:development
#     volumes:
#       - ./:/var/www/html
#     ports:
#       - ${WEB_PORT:-8010}:80
#     restart: unless-stopped
#     networks:
#       - laravel
#     depends_on:
#       - php

#   mysql:
#     build:
#       context: ./docker/mysql
#       dockerfile: Dockerfile
#     image: ${BASE_TAG:-laravel}/mysql:development
#     volumes:
# #      - ./database/mysql:/var/lib/mysql
#       - mysql_data:/var/lib/mysql
#     restart: unless-stopped
#     ports:
#       - ${DB_PORT_DOCK:-3307}:3306
#     environment:
#       - MYSQL_DATABASE=${DB_DATABASE}
#       - MYSQL_USER=${DB_USERNAME}
#       - MYSQL_PASSWORD=${DB_PASSWORD}
#       - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
#       - TZ=${TZ:-Africa/Lagos}
#     networks:
#       - laravel

#   php:
#     build:
#       context: ./docker/php
#       dockerfile: Dockerfile
#     image: ${BASE_TAG:-laravel}/php-fpm:development
#     environment:
#       - DB_HOST=mysql
#       - APP_URL=0.0.0.0:8019
#     volumes:
#       - ./:/var/www/html
#     networks:
#       - laravel
#     depends_on:
#       - mysql

# #  redis:
# #    build: ./docker/redis
# #    ports:
# #      - "${REDIS_PORT:-6379}:6379"
# #    restart: unless-stopped
# #    networks:
# #      - laravel

#   portainer:
#     image: portainer/portainer
#     container_name: "${BASE_TAG:-laravel}_portainer"
#     command: --templates http://templates/templates.json --host=unix:///var/run/docker.sock
#     networks:
#       - laravel
#     ports:
#       - ${PORTAINER_PORT:-9001}:9000
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock

# #  horizon:
# #    build:
# #      context: ./docker/horizon
# #      dockerfile: Dockerfile
# #    image: ${BASE_TAG:-laravel}/horizon:development
# #    volumes:
# #      - ./:/var/www/html
# #    networks:
# #      - laravel

# #  cron:
# #    build:
# #      context: ./docker/cron
# #      dockerfile: Dockerfile
# #    image: ${BASE_TAG:-laravel}/cron:development
# #    volumes:
# #      - ./:/var/www/html
# #      - /tmp:/tmp
# #
# #  node:
# #    build:
# #      context: ./docker/node
# #      dockerfile: Dockerfile
# #    image: ${BASE_TAG:-laravel}/node:development
# #    volumes:
# #      - ./:/var/www/html
 

# networks:
#   laravel:
#     driver: "bridge"
# volumes:
#   mysql_data:
